#ifndef __HDLC_H__
#define __HDLC_H__
/*===========================================================================

          ARM Boot Downloader Header File

DESCRIPTION
  This file contains global declarations and external references
  for the boot block downloader facility specific to the ARM.

Copyright (c) 2007      by QUALCOMM Incorporated.  All Rights Reserved.
===========================================================================*/

#define MODEM_MDM6600
#define MODEM_ESC6270

/*===========================================================================
                    BOOT COMMON TYPE DECLARATIONS
===========================================================================*/

typedef  unsigned char      boolean;     /* Boolean value type. */

typedef  unsigned long int  uint32;      /* Unsigned 32 bit value */
typedef  unsigned short     uint16;      /* Unsigned 16 bit value */
typedef  unsigned char      uint8;       /* Unsigned 8  bit value */

typedef  signed long int    int32;       /* Signed 32 bit value */
typedef  signed short       int16;       /* Signed 16 bit value */
typedef  signed char        int8;        /* Signed 8  bit value */

typedef  unsigned char      byte;        /* Unsigned 8  bit value type. */
typedef  unsigned short     word;        /* Unsinged 16 bit value type. */
typedef  unsigned long      dword;       /* Unsigned 32 bit value type. */

typedef  const char		*LPCSTR;
typedef  byte			*LPBYTE;


/*===========================================================================
                     DEFINE VALUES
===========================================================================*/
#ifndef TRUE
#define TRUE  1
#endif

#ifndef FALSE
#define FALSE  0
#endif

/*===========================================================================
                      PUBLIC DATA DECLARATIONS
===========================================================================*/

/* Status Code Enumeration
   This lists the status result codes passed around in the program.

   This enum is used to index a table of response packets, so these
   values map exactly to possible responses. */

typedef enum
  {
  ACK,                    /* Success. Send an acknowledgement.           */
  NAK_INVALID_FCS,        /* Failure: invalid frame check sequence.      */
  NAK_INVALID_DEST,       /* Failure: destination address is invalid.    */
  NAK_INVALID_LEN,        /* Failure: operation length is invalid.       */
  NAK_EARLY_END,          /* Failure: packet was too short for this cmd. */
  NAK_TOO_LARGE,          /* Failure: packet was too long for my buffer. */
  NAK_INVALID_CMD,        /* Failure: packet command code was unknown.   */
  NAK_FAILED,             /* Failure: operation did not succeed.         */
  NAK_WRONG_IID,          /* Failure: intelligent ID code was wrong.     */
  NAK_BAD_VPP,            /* Failure: programming voltage out of spec    */
  NAK_OP_NOT_PERMITTED,   /* Failure: memory dump not permitted          */
#ifdef FEATURE_DLOAD_MEM_DEBUG
  NAK_INVALID_ADDR,       /* Failure: invalid address for a memory read  */
#endif
  NAK_VERIFY_FAILED,      /* Failure: readback verify did not match      */
  NAK_NO_SEC_CODE,        /* Failure: not permitted without unlock       */
  NAK_BAD_SEC_CODE        /* Failure: invalid security code              */
  } response_code_type;

/*===========================================================================
                     EXTERNAL DEFINITIONS FOR MODULE
===========================================================================*/

/*===========================================================================
            LOCAL DEFINITIONS AND DECLARATIONS FOR MODULE

This section contains local definitions for constants, macros, types,
variables and other items needed by this module.
===========================================================================*/

/* The protocol allows the implementation to place an arbitrary limit on
   how large a data write packet can be.  This value shouldn't be too
   small, for efficiency reasons, but can't be bigger than the memory
   buffer we can allocate.  Here we pick a nice, arbitrary value of
   512 bytes. */
#define  MAX_WRITE_SIZE       (0x200)

/* These variables are generated by the linker, which give the locations
   of memory for which the phone code resides.  This serves as a base for which
   we can zero out memory and use as a packet buffer, as well as code
   downloading */

/* The addresses below allow for armprg to be loaded anywhere between 0x0 and
   32MB. The packet buffer will be just below 32MB. */

/* area for download packet, etc. = 2K */
#define  PKT_BUF_SIZE           (0x800)
#define  PACKED __packed
#define  B_PTR( var )  ( (byte *) (void *) &(var) )


/* Async HDLC achieves data transparency at the byte level by using
   two special values. The first is a flag value which begins and ends
   every packet: */
#define  ASYNC_HDLC_FLAG      0x7e

/* The flag value might appear in the data.  If it does, it is sent as
   a two-byte sequence consisting of a special escape value followed by
   the flag value XORed with 0x20.  This gives a special meaning to the
   escape character, so if it appears in the data it is itself escaped
   in the same way. */
#define  ASYNC_HDLC_ESC       0x7d
#define  ASYNC_HDLC_ESC_MASK  0x20

/* Each packet sent or received in this download protocol begins with a
   one-byte command code chosen from the following list.  Each packet
   type is either received by the phone or transmitted by the phone, but
   not both. */

/*lint -e749  Some values in this local enum are not used in this program. */
/*lint -esym(751,cmd_code_type) and in fact this enum itself is not used. */
typedef enum
{
	CMD_WRITE  = 0x01,   /* Write a block of data to memory (received)    */
	CMD_ACK    = 0x02,   /* Acknowledge receiving a packet  (transmitted) */
	CMD_NAK    = 0x03,   /* Acknowledge a bad packet        (transmitted) */
	CMD_ERASE  = 0x04,   /* Erase a block of memory         (received)    */
	CMD_GO     = 0x05,   /* Begin execution at an address   (received)    */
	CMD_NOP    = 0x06,   /* No operation, for debug         (received)    */
	CMD_PREQ   = 0x07,   /* Request implementation info     (received)    */
	CMD_PARAMS = 0x08,   /* Provide implementation info     (transmitted) */
	CMD_DUMP   = 0x09,   /* Debug: dump a block of memory   (received)    */
	CMD_RESET  = 0x0A,   /* Reset the phone                 (received)    */
	CMD_UNLOCK = 0x0B,   /* Unlock access to secured ops    (received)    */
	CMD_VERREQ = 0x0C,   /* Request software version info   (received)    */
	CMD_VERRSP = 0x0D,   /* Provide software version info   (transmitted) */
	CMD_PWROFF = 0x0E,   /* Turn phone power off            (received)    */
	CMD_WRITE_32BIT = 0x0F,  /* Write a block of data to 32-bit memory
	                          address (received)                        */
	CMD_MEM_DEBUG_QUERY = 0x10, /* Memory debug query       (received)    */
	CMD_MEM_DEBUG_INFO  = 0x11, /* Memory debug info        (transmitted) */
	CMD_MEM_READ_REQ    = 0x12, /* Memory read request      (received)    */
	CMD_MEM_READ_RESP   = 0x13, /* Memory read response     (transmitted) */
	CMD_DLOAD_SWITCH    = 0x3A,
	MAX_CMD_CODE_TYPE   = 0x7FFFFFFF      /**< To ensure it's 32 bits wide         */
} cmd_code_type;


/* For the received packets, we need the minimum length of a valid packet
   of that type (except where the packet is only a command code). Note,
   size is in bytes */

#define  WRITE_SIZ   8  /* Minimum size of the Write packet */
#define  ERASE_SIZ   9  /* Total size of the Erase packet   */
#define  GO_SIZ      7  /* Total size of the Go packet      */
#define  UNLOCK_SIZ  9  /* Total size of the unlock packet  */
#define  WRITE_32BIT_SIZ   9  /* Minimum size of the Write_32bit packet */

/* Maximum size of a received packet. */
#define  MAX_PACKET_LEN    PKT_BUF_SIZE

/* Minimum size of a received packet. */
#define  MIN_PACKET_LEN    3        /* 2 bytes CRC + 1 byte command code */

/*-------------------------------------------------------------------------
 * New Method to get data from the underlying driver.
 *-------------------------------------------------------------------------*/
typedef enum
{
	DLOAD_HDLC_IDLE_STATE,                      /**< Initial State of HDLC state machine */
	DLOAD_HDLC_GOT_FLAG,                        /**< Got Flag                            */
	DLOAD_HDLC_MSG_BODY_STATE,                  /**< State of HDLC when receiving data   */
	MAX_DLOAD_HLDC_STATE_TYPE = 0x7FFFFFFF      /**< To ensure it's 32 bits wide         */
}dload_hdlc_state_type;

struct   incoming_packet
{
	uint32     length;                   /** Number of bytes in buffer.            */
	uint32     start_location;           /** Location where the valid data starts  */
	uint32     end_location;             /** Location where the valid data ends    */
	uint32     step_crc;                 /** CRC on the incoming data         */
	uint32     packet_ready;             /** Is data in the packet ready      */
	byte       buffer[MAX_PACKET_LEN];   /** Data in the buffer.              */
};

/*-------------------------------------------------------------------------
 * New Method to get data from the underlying driver.
 *-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*/

/* These packets are the same every time they are transmitted by the phone,
   so we can use pre-computed "canned" messages.  All byte-stuffing required
   by the protocol for transparency has already been done.  Each packet ends
   with a flag, which is both transmitted and used as the termination
   indicator for these arrays. */

static const byte rsp_ack[] =                   /* ACK */
{
	CMD_ACK,             /* ACK type */
	0x6a,                /* CRC, MSB */
	0xd3,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_invalid_fcs[] =       /* NAK_INVALID_FCS */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x01,                /* Reason code, LSB */
	0x21,                /* CRC, MSB */
	0x38,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_invalid_dest[] =      /* NAK_INVALID_DEST */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x02,                /* Reason code, LSB */
	0xba,                /* CRC, MSB */
	0x0a,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_invalid_len[] =       /* NAK_INVALID_LEN */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x03,                /* Reason code, LSB */
	0x33,                /* CRC, MSB */
	0x1b,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_early_end[] =         /* NAK_EARLY_END */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x04,                /* Reason code, LSB */
	0x8c,                /* CRC, MSB */
	0x6f,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_too_large[] =         /* NAK_TOO_LARGE */
{
	CMD_NAK,                      /* NACK type */
	0x00,                         /* Reason code, MSB */
	0x05,                         /* Reason code, LSB */
	0x05,                         /* CRC, MSB */
	ASYNC_HDLC_ESC,
	0x7e ^ ASYNC_HDLC_ESC_MASK,   /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_invalid_cmd[] =       /* NAK_INVALID_CMD */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x06,                /* Reason code, LSB */
	0x9e,                /* CRC, MSB */
	0x4c,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_failed[] =            /* NAK_FAILED */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x07,                /* Reason code, LSB */
	0x17,                /* CRC, MSB */
	0x5d,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_wrong_iid[] =         /* NAK_WRONG_IID */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x08,                /* Reason code, LSB */
	0xe0,                /* CRC, MSB */
	0xa5,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_bad_vpp[] =           /* NAK_BAD_VPP */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x09,                /* Reason code, LSB */
	0x69,                /* CRC, MSB */
	0xb4,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_verify_failed[] =     /* NAK_VERIFY_FAILED */
{
	CMD_NAK,             /* NACK type */
	0x00,                /* Reason code, MSB */
	0x0a,                /* Reason code, LSB */
	0xf2,                /* CRC, MSB */
	0x86,                /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_no_sec_code[] =          /* NAK_NO_SEC_CODE */
{
	CMD_NAK,    /* NACK type */
	0x000,      /* Reason code, MSB */
	0x00B,      /* Reason code, LSB */
	0x07B,      /* CRC, MSB */
	0x097,      /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_bad_sec_code[] =        /* NAK_BAD_SEC_CODE */
{
	CMD_NAK,    /* NACK type */
	0x000,      /* Reason code, MSB */
	0x00C,      /* Reason code, LSB */
	0x0C4,      /* CRC, MSB */
	0x0E3,      /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

static const byte rsp_nak_op_not_permitted[] =      /* NAK_OP_NOT_PERMITTED */
{
	CMD_NAK,    /* NACK type */
	0x000,      /* Reason code, MSB */
	0x00E,      /* Reason code, LSB */
	0x0,      /* CRC, MSB */
	0x0,      /* CRC, LSB */
	ASYNC_HDLC_FLAG
};

/*-------------------------------------------------------------------------*/

/* This table translates a response code into a pointer to a canned
   response packet.  The table must be in the same order as the
   response_code_type enum. */

static const byte * const response_table[] =
{
	rsp_ack,
	rsp_nak_invalid_fcs,
	rsp_nak_invalid_dest,
	rsp_nak_invalid_len,
	rsp_nak_early_end,
	rsp_nak_too_large,
	rsp_nak_invalid_cmd,
	rsp_nak_failed,
	rsp_nak_wrong_iid,
	rsp_nak_bad_vpp,
	rsp_nak_op_not_permitted,
	rsp_nak_verify_failed,
	rsp_nak_no_sec_code,
	rsp_nak_bad_sec_code
};

/*-------------------------------------------------------------------------*/

/* Other packets must be built up on the fly.  This data type and the
      associated macros support dynamic construction of a packet.  */

/* According to the protocol spec, a version string can be at most 20 bytes */
#define  MAX_VERSTRING_LEN    (20)

#define  ROOM_FOR_CRC   (4)         /* Allow this much room for the CRC,
                                       including worst-case expansion due
                                       to byte-stuffing */
#define  ROOM_FOR_FLAG  (1)         /* Allow this much room for trailing flag */

/* With the memory debug feature, the max data length is 2KB, plus 1 byte for
 * for command, 4 bytes for adress and 2 bytes for length of the data
 */

/* The buffer size for request packets.*/
#define  MAX_REQUEST_LEN  (1+2+MAX_WRITE_SIZE*2+ROOM_FOR_CRC+ROOM_FOR_FLAG)
                           /* 1 = command code
                              2 = fixed fields of packet, version and len */

typedef struct
{
	uint32      length;                 /* Length of packet so far */
	uint32      broken;                 /* Set if the packet can't be built */
	byte        buf[MAX_REQUEST_LEN];  /* The packet under construction */
} pkt_buffer_type;

/*-------------------------------------------------------------------------
 * New Method to get data from the underlying driver.
 *-------------------------------------------------------------------------*/
//#define  DBL_START_ADDR  0x70800000//40//0x78010000
#if 0
#if defined (LSI6410_SATURN)
#define  DBL_START_ADDR  0x78010000//40//0x78010000
#elif defined(MODEM_MDM6600) || defined(CP_MSM7XXX)
#define  DBL_START_ADDR	0x20012000
#define  MAX_DBL_PKT_SIZE 50
#elif defined (UNIV6442)
#define  DBL_START_ADDR  0x70800000
#else
#define  DBL_START_ADDR  0x70800000//40//0x78010000
#endif
#endif

#if defined (UNIV6442)
#define  MAX_DBL_PKT_SIZE 0x40
#else
#define  MAX_DBL_PKT_SIZE 50
#endif

#define  MAX_DLOAD_TIME_TICK 1000

typedef enum
{
	DLOAD_ACK_STATE,
	DLOAD_PARA_STATE,
	DLOAD_WRITE_STATE,
	DLOAD_GO_STATE
} dload_state_type;

typedef struct
{
	uint32      length;
	uint32      addr;
	byte		  *ptr;
	byte        buf[MAX_WRITE_SIZE * MAX_DBL_PKT_SIZE * 2];
} dload_buffer_type;
#define MAX_RETRY_COUNT       1
#define MAX_ACK_COUNT          3

struct boot_data_list
{
	struct incoming_packet packet_data;
	dload_hdlc_state_type  hdlc_curr_state;
	uint32			hdlc_escape_state;

	/* Define the data structure in ZI section so we don't overflow the stack */
	pkt_buffer_type params_buf;

	unsigned int dbl_size;

	dload_buffer_type tx_pkt;

	int dload_state;
	int ack_cnt;
	int retry_cnt;
	int exit;
	int fd_uart0;
	int uart_read_cnt;
	int dbl_start_addr;
	int use_uart;
};

/*===========================================================================
                      PUBLIC FUNCTION DECLARATIONS
===========================================================================*/
#if defined(MODEM_MDM6600) || defined(MODEM_ESC6270)
extern struct boot_data_list boot_data[];
void add_byte_to_packet(pkt_buffer_type  *pkt, const byte val);
void finish_building_packet(pkt_buffer_type  *pkt);
void start_building_packet(pkt_buffer_type  *pkt);
void dload_uart_transmit_byte(int type, byte  chr);
void transmit_byte(int type, byte data);
//void transmit_resopnse(int type, response_code_type rsp);
void dload_uart_receive_byte(int type, byte *buf, uint32 *length);
void transmit_packet(int type, pkt_buffer_type *pkt);
void nop_req(int type);
void param_req(int type);
void write_32bit_req(int type, uint32 addr, byte *buf, uint32 len);
void go_req(int type);
void nak_cmd(int type, byte	 *cmd_buf, uint32 cmd_len);
void pres_cmd(int type, byte *cmd_buf, uint32 cmd_len);
void ack_cmd(int type);
void dload_packet_init (int type);
void dload_enable_transmission(int type);
void dload_packet_handle_incoming_data(int type, boolean escape_char, byte ch);
void dload_hdlc_init (int type, int size, int dbl_addr, int use_uart);
void dload_hdlc_handle_data (int type, byte ch);
void dload_hdlc_handle_incoming_byte (int type, byte ch);
uint32 dload_get_data_from_device(int type);
void dload_process_incoming_packets(int type);

#else

extern dload_buffer_type tx_pkt;
extern struct incoming_packet packet_data;
extern int g_exit;
extern int fd_uart0;

void add_byte_to_packet(pkt_buffer_type  *pkt, const byte val);
void finish_building_packet(pkt_buffer_type  *pkt);
void start_building_packet(pkt_buffer_type  *pkt);
void dload_uart_transmit_byte(byte  chr);
void transmit_byte(byte data);
void transmit_resopnse(response_code_type rsp);
void dload_uart_receive_byte(byte *buf, uint32 *length);
void transmit_packet(pkt_buffer_type *pkt);
void nop_req(void);
void param_req(void);
void write_32bit_req(uint32 addr, byte *buf, uint32 len);
void go_req();
void nak_cmd(byte	 *cmd_buf, uint32 cmd_len);
void pres_cmd(byte *cmd_buf, uint32 cmd_len);
void ack_cmd(void);
void dload_packet_init (void);
void dload_enable_transmission(void);
void dload_packet_handle_incoming_data(boolean escape_char, byte ch);
void dload_hdlc_init (int size, int dbl_addr, int use_uart);
void dload_hdlc_handle_data (byte ch);
void dload_hdlc_handle_incoming_byte (byte ch);
uint32 dload_get_data_from_device();
void dload_process_incoming_packets(void);
#endif

#endif /* __DLOAD_HDLC_H__ */
